In [1]:
import pandas as pd
import geopandas as gpd
import re
import seaborn as sns
import datetime as dt
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Reading In Rental List - Magnum and R&R

In [4]:
#Reading Mastr shapefile
shapefile = gpd.read_file("zip://BLM Master 3-2021.zip")
shapefile.columns

Index(['lot_no', 'LEASE_NO', 'EFFECTIVE', 'COUNTY', 'ST', 'Ownership',
       'GeneralLoc', 'Due_Year', 'Acres', 'COMMENTS', 'Est_Bonus', 'Exp_date',
       'Comments_1', 'Shape_Leng', 'Shape_Area', 'geometry'],
      dtype='object')

# Filter Expired Acreage

In [5]:
todaysDate = dt.datetime.now()

todaysDate = todaysDate.strftime('%Y-%m-%d')

In [6]:
todaysDate

'2021-05-28'

In [7]:
activeAcreageShape = shapefile.loc[shapefile['Exp_date']>todaysDate]

### Looking at lenghts of filtered shapefiles to make sure it worked

In [8]:
shapefile.shape[0]
activeAcreageShape.shape[0]

1876

986

In [9]:
activeAcreageShape.head()

,lot_no,LEASE_NO,EFFECTIVE,COUNTY,ST,Ownership,GeneralLoc,Due_Year,Acres,COMMENTS,Est_Bonus,Exp_date,Comments_1,Shape_Leng,Shape_Area,geometry
38,0,MTM101455,2011-07-01,RICHLAND,MT,Magnum Producing LP,None,2021.0,10.32,None,302,2021-07-01,None,3853.718897,3.526854e+05,MULTIPOLYGON Z (((-11709062.157 6118921.792 0....
39,0,MTM101456,2011-07-01,RICHLAND,MT,Magnum Producing LP,None,2021.0,5.88,None,336,2021-07-01,None,1781.457067,1.260800e+05,"POLYGON Z ((-11686184.000 6120992.000 0.000, -..."
40,0,MTM101458,2011-07-01,RICHLAND,MT,Magnum Producing LP,None,2021.0,40.00,None,780,2021-07-01,None,2418.000000,3.654140e+05,"POLYGON Z ((-11656641.000 6124666.000 0.000, -..."
41,0,MTM101464,2011-07-01,DAWSON,MT,Magnum Producing LP,None,2021.0,320.00,None,212,2021-07-01,None,7128.000000,2.813120e+06,"POLYGON Z ((-11645706.000 6037283.000 0.000, -..."
42,0,MTM101465,2011-07-01,DAWSON,MT,Magnum Producing LP,None,2021.0,318.07,None,152,2021-07-01,None,7130.447346,2.838999e+06,"POLYGON Z ((-11655246.000 6037269.000 0.000, -..."

## Reading In List of Lease Numbers to Extract

In [ ]:
pro

In [12]:
extractDF = pd.read_excel("Meadville/extractionList.xlsx")
extractDF

   ListToFilter    Acres
0    MSES056969   991.78
1    MSES056971    39.78
2    MSES056972  1212.36
3    MSES056973  1157.59
4    MSES056974  1193.71
5    MSES056976  1134.07
6    MSES056977  1144.33
7    MSES056980  1580.28
8    MSES056992   700.94
9    MSES056993   160.57
10   MSES056994   644.32
11   MSES056995   743.24
12   MSES056996   639.32
13   MSES056997   701.80
14   MSES056998   311.94
15   MSES056999   644.72
16   MSES057000   527.52
17   MSES057001   860.39
18   MSES057002   241.22
19   MSES057003   636.03
20   MSES057004   392.74
21   MSES057005    41.17
22   MSES057011   465.98
23   MSES057013   955.50
24   MSES057014    40.00
25   MSES057047   534.10
26   MSES057093   516.00
27    MSES57372  1479.50
28    MSES57386   337.31
29    MSES57371  1084.79
30    MSES57368  1478.63
31    MSES57369  1884.59
32    MSES57370  1829.75

In [13]:
listToExtract = list(extractDF["ListToFilter"])
listToExtract

['MSES056969',
 'MSES056971',
 'MSES056972',
 'MSES056973',
 'MSES056974',
 'MSES056976',
 'MSES056977',
 'MSES056980',
 'MSES056992',
 'MSES056993',
 'MSES056994',
 'MSES056995',
 'MSES056996',
 'MSES056997',
 'MSES056998',
 'MSES056999',
 'MSES057000',
 'MSES057001',
 'MSES057002',
 'MSES057003',
 'MSES057004',
 'MSES057005',
 'MSES057011',
 'MSES057013',
 'MSES057014',
 'MSES057047',
 'MSES057093',
 'MSES57372',
 'MSES57386',
 'MSES57371',
 'MSES57368',
 'MSES57369',
 'MSES57370']

### Getting Extracted Lease Numbers

In [14]:
RRpetrohuntAcreage = activeAcreageShape[activeAcreageShape["LEASE_NO"].isin(listToExtract)]

In [15]:
RRpetrohuntAcreage["Comments_1"].value_counts()

ASSIGNED FROM PETROHUNT IN AUGUST 2019 & NEED TO FILE AN ASSIGNMENT, NEED TO PAY RENTALS                          17
EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & "RE-ASSIGNED FROM PETROHUNT IN AUGUST 2019, NEED TO PAY RENTALS"    16
Name: Comments_1, dtype: int64

### Subdividing extracted list Further

In [16]:
petrohuntsAcreage = RRpetrohuntAcreage[RRpetrohuntAcreage["COMMENTS"]== "ASSIGNED FROM PETROHUNT IN AUGUST 2019 & NEED TO FILE AN ASSIGNMENT, NEED TO PAY RENTALS"]

In [17]:
petrohuntsAcreage['Acres'].sum()

8707.399999999998

In [18]:
rrAcreage = RRpetrohuntAcreage[RRpetrohuntAcreage["COMMENTS"]=="EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & \"RE-ASSIGNED FROM PETROHUNT IN AUGUST 2019, NEED TO PAY RENTALS\""]

In [19]:
rrAcreage['Acres'].sum()

17598.57

In [20]:
rrAcreage["Exp_date"].unique()

array(['2021-11-01', '2021-08-01', '2022-05-01'], dtype=object)

In [66]:

for date in rrAcreage["Exp_date"].unique():
    print(date)
    rrAcreage[rrAcreage["Exp_date"]==date]
    rrAcreage[rrAcreage["Exp_date"]==date].to_file('Shapefiles/{} Exp RR Meadville.shp'.format(date))

2021-11-01

,lot_no,LEASE_NO,EFFECTIVE,COUNTY,ST,Ownership,GeneralLoc,Due_Year,Acres,COMMENTS,Est_Bonus,Exp_date,Comments_1,Shape_Leng,Shape_Area,geometry
528,0,MSES057093,2011-11-01,FRANKLIN,MS,R&R Royalty,None,2021.0,516.0,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,222,2021-11-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,9155.196,2.857452e+06,"POLYGON Z ((-10126224.105 3690878.199 0.000, -..."

2021-08-01

,lot_no,LEASE_NO,EFFECTIVE,COUNTY,ST,Ownership,GeneralLoc,Due_Year,Acres,COMMENTS,Est_Bonus,Exp_date,Comments_1,Shape_Leng,Shape_Area,geometry
1020,0,MSES056969,2011-08-01,AMITE,MS,R&R Royalty,Yes,2021.0,991.78,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,10,2021-08-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,33600.554754,1.086651e+07,MULTIPOLYGON Z (((-10129565.395 3667031.778 0....
1022,0,MSES056971,2011-08-01,AMITE,MS,R&R Royalty,None,2021.0,39.78,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,13,2021-08-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,1899.780425,2.253957e+05,"POLYGON Z ((-10126605.508 3675262.925 0.000, -..."
1023,0,MSES056972,2011-08-01,AMITE,MS,R&R Royalty,None,2021.0,1212.36,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,10,2021-08-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,14211.662988,6.600446e+06,MULTIPOLYGON Z (((-10116658.194 3676741.035 0....
1024,0,MSES056973,2011-08-01,AMITE,MS,R&R Royalty,Yes,2021.0,1157.59,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,32,2021-08-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,19477.048688,6.749633e+06,MULTIPOLYGON Z (((-10122866.950 3677190.863 0....
1025,0,MSES056974,2011-08-01,AMITE,MS,R&R Royalty,None,2021.0,1193.71,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,32,2021-08-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,11540.506011,6.601871e+06,"POLYGON Z ((-10123806.408 3678157.802 0.000, -..."
1026,0,MSES056976,2011-08-01,AMITE,MS,R&R Royalty,None,2021.0,1134.07,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,11,2021-08-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,13578.665944,6.216726e+06,"POLYGON Z ((-10117141.799 3675276.656 0.000, -..."
1027,0,MSES056977,2011-08-01,AMITE,MS,R&R Royalty,None,2021.0,1144.33,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,10,2021-08-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,15447.981117,6.360676e+06,MULTIPOLYGON Z (((-10117180.694 3672315.174 0....
1028,0,MSES056980,2011-08-01,AMITE,MS,R&R Royalty,None,2021.0,1580.28,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,9,2021-08-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,16566.300303,8.707949e+06,"POLYGON Z ((-10112474.062 3678197.598 0.000, -..."
1030,0,MSES057047,2011-08-01,AMITE,MS,R&R Royalty,None,2021.0,534.10,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,12,2021-08-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,8464.761662,3.324599e+06,"POLYGON Z ((-10125239.446 3675078.679 0.000, -..."

2022-05-01

,lot_no,LEASE_NO,EFFECTIVE,COUNTY,ST,Ownership,GeneralLoc,Due_Year,Acres,COMMENTS,Est_Bonus,Exp_date,Comments_1,Shape_Leng,Shape_Area,geometry
1065,0,MSES57368,2012-05-01,FRANKLIN,MS,R&R Royalty,Yes,2022.0,1478.63,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,6,2022-05-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,27564.807261,7.650897e+06,MULTIPOLYGON Z (((-10107277.145 3688089.054 0....
1066,0,MSES57369,2012-05-01,FRANKLIN,MS,R&R Royalty,None,2022.0,1884.59,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,18,2022-05-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,17864.647260,1.084990e+07,"POLYGON Z ((-10111486.202 3687610.844 0.000, -..."
1067,0,MSES57370,2012-05-01,FRANKLIN,MS,R&R Royalty,Yes,2022.0,1829.75,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,18,2022-05-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,22122.470168,1.020531e+07,"POLYGON Z ((-10112426.495 3685740.319 0.000, -..."
1068,0,MSES57371,2012-05-01,FRANKLIN,MS,R&R Royalty,None,2022.0,1084.79,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,4,2022-05-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,27322.608574,6.168097e+06,MULTIPOLYGON Z (((-10108660.891 3682902.391 0....
1071,0,MSES57386,2012-05-01,FRANKLIN,MS,R&R Royalty,None,2022.0,337.31,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,4,2022-05-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,8450.840094,1.655237e+06,MULTIPOLYGON Z (((-10112441.701 3681494.162 0....
1127,0,MSES57372,2012-05-01,FRANKLIN,MS,R&R Royalty,Yes,2022.0,1479.50,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,152,2022-05-01,EXPLORATION AGRMT. MEADVILLE 3D - PETROHUNT & ...,24295.084479,8.194935e+06,MULTIPOLYGON Z (((-10109642.973 3678680.420 0....

## Export Shapefile

In [32]:
#activeAcreageShape.to_file("ActiveAcreage as of {}.shp".format(todaysDate))