In [1]:
import pandas as pd
import geopandas as gpd
import re
import seaborn as sns

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
month = "May"
year = 2021

# Reading In Rental List - Magnum and R&R

In [3]:
#R&R and Magnum Rental List
RRList = pd.read_excel("BLM Rents {} {}.xlsx".format(month, year), header = 4, usecols = 8)
MPLPList = pd.read_excel("BLM Rents {} {}.xlsx".format(month, year), header = 4, usecols = 8, sheet_name = "MPLP")

/anaconda3/lib/python3.6/site-packages/pandas/io/excel.py:527: FutureWarning: Passing in an integer for `usecols` has been deprecated. Please pass in a list of int from 0 to `usecols` inclusive instead.
  usecols = _maybe_convert_usecols(usecols)

In [4]:
#Reading Mastr shapefile
shapefile = gpd.read_file("zip://.zip")
shapefile.columns

DriverError: '/vsizip/Master Shapefile 3-2021.zip' does not exist in the file system, and is not recognized as a supported dataset name.

In [5]:
RRList
MPLPList

,LEASE NO.,COUNTY,STATE,EXPIRATION,ACRES,RENTAL,COUNTY.1,Y/N,Mishaun Comments
0,LAES57452,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1998.57,3998.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
1,LAES57453,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,638.47,1278.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
2,LAES57454,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.63,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
3,LAES57455,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1154.67,2310.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
4,LAES57456,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.32,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
5,LAES57457,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.72,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
6,LAES57458,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.68,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
7,LAES57459,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2022.78,4046.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
8,LAES57460,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.68,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
9,LAES57461,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1273.80,2548.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
10,LAES57462,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,637.40,1276.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
11,LAES57463,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.52,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
12,LAES57464,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,591.10,1184.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
13,LAES57465,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,637.76,1276.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
14,LAES57466,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1274.00,2548.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
15,LAES57467,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2054.08,4110.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
16,LAES57468,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1911.48,3824.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
17,LAES57469,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1588.40,3178.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
18,LAES57470,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2498.37,4998.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
19,LAES57471,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,89.10,180.0,44398.0,NaN,We renewed this blockcontiguous to this in ma...
20,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
21,LAES056818,WINN PARISH,LOUISIANA,2021-08-01,39.55,80.0,NaN,NaN,active shallow production 3+ miles away in wil...
22,LAES056819,WINN PARISH,LOUISIANA,2021-08-01,377.03,756.0,NaN,NaN,active shallow production 3+ miles away in wil...
23,LAES056820,WINN PARISH,LOUISIANA,2021-08-01,757.41,1516.0,NaN,NaN,active shallow production 3+ miles away in wil...
24,LAES056821,WINN PARISH,LOUISIANA,2021-08-01,715.99,1432.0,NaN,NaN,active shallow production 3+ miles away in wil...
25,LAES056822,WINN PARISH,LOUISIANA,2021-08-01,1613.27,3228.0,NaN,NaN,active shallow production 3+ miles away in wil...
26,LAES056823,WINN PARISH,LOUISIANA,2021-08-01,242.37,486.0,NaN,NaN,active shallow production 3+ miles away in wil...
27,LAES056828,WINN PARISH,LOUISIANA,2021-08-01,79.64,160.0,NaN,NaN,active shallow production 3+ miles away in wil...
28,LAES056829,WINN PARISH,LOUISIANA,2021-08-01,79.66,160.0,NaN,NaN,JSB active operator to western part of this ac...
29,LAES056831,WINN PARISH,LOUISIANA,2021-08-01,279.78,560.0,NaN,NaN,JSB active operator to western part of this ac...
...,...,...,...,...,...,...,...,...,...
80,MSES057013,FRANKLIN,MISSISSIPPI,2021-08-01,955.50,1912.0,NaN,NaN,Active welsl near tracts have produced siginif...
81,MSES057014,FRANKLIN,MISSISSIPPI,2021-08-01,40.00,80.0,29034.0,NaN,Active welsl near tracts have produced siginif...
82,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
83,MSES57486,JASPER,MISSISSIPPI,2022-08-01,1501.96,3004.0,NaN,NaN,No active wells or permits neawr tracts - 2 ye...
84,MSES57487,JASPER,MISSISSIPPI,2022-08-01,642.53,1286.0,NaN,NaN,No active wells or permits neawr tracts - 2 ye...
85,MSES57488,JASPER,MISSISSIPPI,2022-08-01,639.56,1280.0,NaN,NaN,No active wells or permits neawr tracts - 2 ye...
86,MSES57489,JASPER,MISSISSIPPI,2022-08-01,210.30,422.0,NaN,NaN,No active wells or permits neawr tracts - 2 ye...
87,MSES57490,JASPER,MISSISSIPPI,2022-08-01,1285.44,2572.0,NaN,NaN,No active wells or permits neawr tracts - 2 ye...
88,MSES57491,JASPER,MISSISSIPPI,2022-08-01,160.00,320.0,8884.0,NaN,No active wells or permits neawr tracts - 2 ye...
89,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
90,MSES056854,SCOTT,MISSISSIPPI,2021-08-01,35.19,72.0,NaN,NaN,no active wells near tracts; no permits
91,MSES056855,SCOTT,MISSISSIPPI,2021-08-01,638.96,1278.0,NaN,NaN,no active wells near tracts; no permits
92,MSES056856,SCOTT,MISSISSIPPI,2021-08-01,159.19,320.0,NaN,NaN,no active wells near tracts; no permits
93,MSES056857,SCOTT,MISSISSIPPI,2021-08-01,199.61,400.0,NaN,NaN,no active wells near tracts; no permits
94,MSES056858,SCOTT,MISSISSIPPI,2021-08-01,60.04,122.0,NaN,NaN,no active wells near tracts; no permits
95,MSES056859,SCOTT,MISSISSIPPI,2021-08-01,543.22,1088.0,NaN,NaN,no active wells near tracts; no permits
96,MSES056860,SCOTT,MISSISSIPPI,2021-08-01,99.54,200.0,NaN,NaN,no active wells near tracts; no permits
97,MSES056861,SCOTT,MISSISSIPPI,2021-08-01,159.38,320.0,NaN,NaN,no active wells near tracts; no permits
98,MSES056862,SCOTT,MISSISSIPPI,2021-08-01,488.92,978.0,NaN,NaN,no active wells near tracts; no permits
99,MSES57475,SCOTT,MISSISSIPPI,2022-08-01,233.00,466.0,NaN,NaN,no active wells near tracts; no permits
100,MSES57476,SCOTT,MISSISSIPPI,2022-08-01,471.91,944.0,NaN,NaN,no active wells near tracts; no permits
101,MSES57477,SCOTT,MISSISSIPPI,2022-08-01,251.13,504.0,NaN,NaN,no active wells near tracts; no permits
102,MSES57478,SCOTT,MISSISSIPPI,2022-08-01,233.29,468.0,NaN,NaN,no active wells near tracts; no permits
103,MSES57492,SCOTT,MISSISSIPPI,2022-08-01,2532.17,5066.0,NaN,NaN,no active wells near tracts; no permits
104,MSES57493,SCOTT,MISSISSIPPI,2022-08-01,1245.75,2492.0,14718.0,NaN,no active wells near tracts; no permits
105,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
106,MSES056966,WILKINSON,MISSISSIPPI,2021-08-01,105.85,212.0,NaN,NaN,active well w/in 1 mi radius of tracts - best ...
107,MSES056967,WILKINSON,MISSISSIPPI,2021-08-01,671.46,1344.0,NaN,NaN,active well w/in 1 mi radius of tracts - best ...
108,MSES056968,WILKINSON,MISSISSIPPI,2021-08-01,34.85,70.0,1626.0,NaN,active well w/in 1 mi radius of tracts - best ...
109,NaN,NaN,NaN,NaT,NaN,138114.0,138114.0,NaN,NaN

,LEASE NO.,COUNTY,STATE,EXPIRATION,ACRES,RENTAL,COUNTY.1,Y/N,Mishaun Comments
0,ARES059276,CLEBURNE,ARKANSAS,2028-08-01,205.00,307.5,NaN,NaN,NaN
1,ARES059277,CLEBURNE,ARKANSAS,2028-08-01,120.00,180.0,NaN,NaN,NaN
2,ARES059278,CLEBURNE,ARKANSAS,2028-08-01,40.00,60.0,NaN,NaN,NaN
3,ARES059293,CLEBURNE,ARKANSAS,2028-08-01,86.03,130.5,678.0,NaN,NaN
4,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
5,ARES059280,VAN BUREN,ARKANSAS,2028-08-01,39.80,60.0,NaN,NaN,NaN
6,ARES059281,VAN BUREN,ARKANSAS,2028-08-01,80.00,120.0,NaN,NaN,NaN
7,ARES059282,VAN BUREN,ARKANSAS,2028-08-01,364.38,547.5,NaN,NaN,NaN
8,ARES059283,VAN BUREN,ARKANSAS,2028-08-01,122.38,184.5,NaN,NaN,NaN
9,ARES059285,VAN BUREN,ARKANSAS,2028-08-01,40.00,60.0,NaN,NaN,NaN
10,ARES059286,VAN BUREN,ARKANSAS,2028-08-01,67.50,102.0,NaN,NaN,NaN
11,ARES059287,VAN BUREN,ARKANSAS,2028-08-01,40.00,60.0,NaN,NaN,NaN
12,ARES059288,VAN BUREN,ARKANSAS,2028-08-01,40.00,60.0,NaN,NaN,NaN
13,ARES059289,VAN BUREN,ARKANSAS,2028-08-01,80.00,120.0,NaN,NaN,NaN
14,ARES059290,VAN BUREN,ARKANSAS,2028-08-01,120.00,180.0,NaN,NaN,NaN
15,ARES059291,VAN BUREN,ARKANSAS,2028-08-01,80.00,120.0,NaN,NaN,NaN
16,ARES059292,VAN BUREN,ARKANSAS,2028-08-01,40.00,60.0,NaN,NaN,NaN
17,ARES059299,VAN BUREN,ARKANSAS,2028-08-01,39.59,60.0,1734.0,NaN,NaN
18,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
19,COC78348,RIO BLANCO,COLORADO,2027-08-01,1787.82,2682.0,NaN,NaN,NaN
20,COC78349,RIO BLANCO,COLORADO,2027-08-01,1808.82,2713.5,NaN,NaN,NaN
21,COC78350,RIO BLANCO,COLORADO,2027-08-01,1873.26,2811.0,NaN,NaN,NaN
22,COC78351,RIO BLANCO,COLORADO,2027-08-01,1917.52,2877.0,NaN,NaN,NaN
23,COC78352,RIO BLANCO,COLORADO,2027-08-01,1914.96,2872.5,NaN,NaN,NaN
24,COC78353,RIO BLANCO,COLORADO,2027-08-01,1834.59,2752.5,NaN,NaN,NaN
25,COC78355,RIO BLANCO,COLORADO,2027-08-01,640.00,960.0,NaN,NaN,NaN
26,COC78356,RIO BLANCO,COLORADO,2027-08-01,1440.00,2160.0,NaN,NaN,NaN
27,COC78357,RIO BLANCO,COLORADO,2027-08-01,2230.00,3345.0,NaN,NaN,NaN
28,COC78358,RIO BLANCO,COLORADO,2027-08-01,1920.40,2881.5,NaN,NaN,NaN
29,COC78359,RIO BLANCO,COLORADO,2027-08-01,2164.84,3247.5,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
52,MSES056949,HARRISON,MISSISSIPPI,2021-08-01,359.33,720.0,NaN,NaN,No active wells in the county - no permits - 1...
53,MSES056950,HARRISON,MISSISSIPPI,2021-08-01,399.53,800.0,NaN,NaN,No active wells in the county - no permits - 1...
54,MSES056951,HARRISON,MISSISSIPPI,2021-08-01,1236.33,2474.0,NaN,NaN,No active wells in the county - no permits - 1...
55,MSES056955,HARRISON,MISSISSIPPI,2021-08-01,1278.00,2556.0,NaN,NaN,No active wells in the county - no permits - 1...
56,MSES056956,HARRISON,MISSISSIPPI,2021-08-01,1277.40,2556.0,NaN,NaN,No active wells in the county - no permits - 1...
57,MSES056960,HARRISON,MISSISSIPPI,2021-08-01,1101.65,2204.0,NaN,NaN,No active wells in the county - no permits - 1...
58,MSES056961,HARRISON,MISSISSIPPI,2021-08-01,635.05,1272.0,12582.0,NaN,No active wells in the county - no permits - 1...
59,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
60,MSES056947,JACKSON,MISSISSIPPI,2021-08-01,640.00,1280.0,NaN,NaN,No active wells in the county - no permits - 1...
61,MSES056948,JACKSON,MISSISSIPPI,2021-08-01,537.44,1076.0,NaN,NaN,No active wells in the county - no permits - 1...
62,MSES056952,JACKSON,MISSISSIPPI,2021-08-01,1154.53,2310.0,NaN,NaN,No active wells in the county - no permits - 1...
63,MSES056953,JACKSON,MISSISSIPPI,2021-08-01,804.76,1610.0,NaN,NaN,No active wells in the county - no permits - 1...
64,MSES056954,JACKSON,MISSISSIPPI,2021-08-01,957.28,1916.0,NaN,NaN,No active wells in the county - no permits - 1...
65,MSES056958,JACKSON,MISSISSIPPI,2021-08-01,1002.97,2006.0,NaN,NaN,No active wells in the county - no permits - 1...
66,MSES056962,JACKSON,MISSISSIPPI,2021-08-01,993.08,1988.0,NaN,NaN,No active wells in the county - no permits - 1...
67,MSES056957,JACKSON,MISSISSIPPI,2021-08-01,1324.52,2650.0,NaN,NaN,No active wells in the county - no permits - 1...
68,MSES056959,JACKSON,MISSISSIPPI,2021-08-01,834.25,1670.0,16506.0,NaN,No active wells in the county - no permits - 1...
69,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
70,NDM101479,MCKENZIE,NORTH DAKOTA,2021-08-01,120.69,242.0,242.0,NaN,NaN
71,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
72,UTU92328,SANPETE,UTAH,2027-08-01,1239.20,1860.0,NaN,NaN,NaN
73,UTU92330,SANPETE,UTAH,2027-08-01,1300.17,1951.5,3811.5,NaN,NaN
74,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
75,UTU92311,SEVIER,UTAH,2027-08-01,200.00,300.0,NaN,NaN,NaN
76,UTU92312,SEVIER,UTAH,2027-08-01,346.74,520.5,NaN,NaN,NaN
77,UTU92313,SEVIER,UTAH,2027-08-01,200.00,300.0,NaN,NaN,NaN
78,UTU92314,SEVIER,UTAH,2027-08-01,1482.76,2224.5,NaN,NaN,NaN
79,UTU92315,SEVIER,UTAH,2027-08-01,2032.52,3049.5,NaN,NaN,NaN
80,UTU92316,SEVIER,UTAH,2027-08-01,677.60,1017.0,7411.5,NaN,NaN
81,NaN,NaN,NaN,NaT,NaN,97849.0,97849.0,NaN,NaN

## Concatenating Magnum and RR Into 1 Dataframe
### Cleaning Dataframe by removing null rows, subtotal rows, etc

In [6]:
#concat magnum and r&r rental list
RentalList = pd.concat([RRList, MPLPList])

In [7]:
#dropping rows with null values for lease number and county
RentalList.dropna(subset = ["LEASE NO.", "COUNTY"], how = 'all', inplace = True)

#resetting index
RentalList.reset_index(inplace = True, drop = True)

RentalList

,LEASE NO.,COUNTY,STATE,EXPIRATION,ACRES,RENTAL,COUNTY.1,Y/N,Mishaun Comments
0,LAES57452,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1998.57,3998.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
1,LAES57453,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,638.47,1278.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
2,LAES57454,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.63,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
3,LAES57455,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1154.67,2310.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
4,LAES57456,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.32,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
5,LAES57457,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.72,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
6,LAES57458,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.68,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
7,LAES57459,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2022.78,4046.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
8,LAES57460,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.68,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
9,LAES57461,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1273.80,2548.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
10,LAES57462,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,637.40,1276.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
11,LAES57463,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.52,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
12,LAES57464,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,591.10,1184.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
13,LAES57465,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,637.76,1276.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
14,LAES57466,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1274.00,2548.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
15,LAES57467,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2054.08,4110.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
16,LAES57468,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1911.48,3824.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
17,LAES57469,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1588.40,3178.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
18,LAES57470,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2498.37,4998.0,NaN,NaN,We renewed this blockcontiguous to this in ma...
19,LAES57471,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,89.10,180.0,44398.0,NaN,We renewed this blockcontiguous to this in ma...
20,LAES056818,WINN PARISH,LOUISIANA,2021-08-01,39.55,80.0,NaN,NaN,active shallow production 3+ miles away in wil...
21,LAES056819,WINN PARISH,LOUISIANA,2021-08-01,377.03,756.0,NaN,NaN,active shallow production 3+ miles away in wil...
22,LAES056820,WINN PARISH,LOUISIANA,2021-08-01,757.41,1516.0,NaN,NaN,active shallow production 3+ miles away in wil...
23,LAES056821,WINN PARISH,LOUISIANA,2021-08-01,715.99,1432.0,NaN,NaN,active shallow production 3+ miles away in wil...
24,LAES056822,WINN PARISH,LOUISIANA,2021-08-01,1613.27,3228.0,NaN,NaN,active shallow production 3+ miles away in wil...
25,LAES056823,WINN PARISH,LOUISIANA,2021-08-01,242.37,486.0,NaN,NaN,active shallow production 3+ miles away in wil...
26,LAES056828,WINN PARISH,LOUISIANA,2021-08-01,79.64,160.0,NaN,NaN,active shallow production 3+ miles away in wil...
27,LAES056829,WINN PARISH,LOUISIANA,2021-08-01,79.66,160.0,NaN,NaN,JSB active operator to western part of this ac...
28,LAES056831,WINN PARISH,LOUISIANA,2021-08-01,279.78,560.0,NaN,NaN,JSB active operator to western part of this ac...
29,LAES056832,WINN PARISH,LOUISIANA,2021-08-01,79.69,160.0,NaN,NaN,JSB active operator to western part of this ac...
...,...,...,...,...,...,...,...,...,...
144,MSES57494,FORREST,MISSISSIPPI,2022-08-01,2414.88,4830.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...
145,MSES57495,FORREST,MISSISSIPPI,2022-08-01,1640.72,3282.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...
146,MSES57496,FORREST,MISSISSIPPI,2022-08-01,80.00,160.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...
147,MSES57497,FORREST,MISSISSIPPI,2022-08-01,200.00,400.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...
148,MSES57498,FORREST,MISSISSIPPI,2022-08-01,40.00,80.0,8752.0,NaN,active shallow prod 1 -3 miles away from tract...
149,MSES056949,HARRISON,MISSISSIPPI,2021-08-01,359.33,720.0,NaN,NaN,No active wells in the county - no permits - 1...
150,MSES056950,HARRISON,MISSISSIPPI,2021-08-01,399.53,800.0,NaN,NaN,No active wells in the county - no permits - 1...
151,MSES056951,HARRISON,MISSISSIPPI,2021-08-01,1236.33,2474.0,NaN,NaN,No active wells in the county - no permits - 1...
152,MSES056955,HARRISON,MISSISSIPPI,2021-08-01,1278.00,2556.0,NaN,NaN,No active wells in the county - no permits - 1...
153,MSES056956,HARRISON,MISSISSIPPI,2021-08-01,1277.40,2556.0,NaN,NaN,No active wells in the county - no permits - 1...
154,MSES056960,HARRISON,MISSISSIPPI,2021-08-01,1101.65,2204.0,NaN,NaN,No active wells in the county - no permits - 1...
155,MSES056961,HARRISON,MISSISSIPPI,2021-08-01,635.05,1272.0,12582.0,NaN,No active wells in the county - no permits - 1...
156,MSES056947,JACKSON,MISSISSIPPI,2021-08-01,640.00,1280.0,NaN,NaN,No active wells in the county - no permits - 1...
157,MSES056948,JACKSON,MISSISSIPPI,2021-08-01,537.44,1076.0,NaN,NaN,No active wells in the county - no permits - 1...
158,MSES056952,JACKSON,MISSISSIPPI,2021-08-01,1154.53,2310.0,NaN,NaN,No active wells in the county - no permits - 1...
159,MSES056953,JACKSON,MISSISSIPPI,2021-08-01,804.76,1610.0,NaN,NaN,No active wells in the county - no permits - 1...
160,MSES056954,JACKSON,MISSISSIPPI,2021-08-01,957.28,1916.0,NaN,NaN,No active wells in the county - no permits - 1...
161,MSES056958,JACKSON,MISSISSIPPI,2021-08-01,1002.97,2006.0,NaN,NaN,No active wells in the county - no permits - 1...
162,MSES056962,JACKSON,MISSISSIPPI,2021-08-01,993.08,1988.0,NaN,NaN,No active wells in the county - no permits - 1...
163,MSES056957,JACKSON,MISSISSIPPI,2021-08-01,1324.52,2650.0,NaN,NaN,No active wells in the county - no permits - 1...
164,MSES056959,JACKSON,MISSISSIPPI,2021-08-01,834.25,1670.0,16506.0,NaN,No active wells in the county - no permits - 1...
165,NDM101479,MCKENZIE,NORTH DAKOTA,2021-08-01,120.69,242.0,242.0,NaN,NaN
166,UTU92328,SANPETE,UTAH,2027-08-01,1239.20,1860.0,NaN,NaN,NaN
167,UTU92330,SANPETE,UTAH,2027-08-01,1300.17,1951.5,3811.5,NaN,NaN
168,UTU92311,SEVIER,UTAH,2027-08-01,200.00,300.0,NaN,NaN,NaN
169,UTU92312,SEVIER,UTAH,2027-08-01,346.74,520.5,NaN,NaN,NaN
170,UTU92313,SEVIER,UTAH,2027-08-01,200.00,300.0,NaN,NaN,NaN
171,UTU92314,SEVIER,UTAH,2027-08-01,1482.76,2224.5,NaN,NaN,NaN
172,UTU92315,SEVIER,UTAH,2027-08-01,2032.52,3049.5,NaN,NaN,NaN
173,UTU92316,SEVIER,UTAH,2027-08-01,677.60,1017.0,7411.5,NaN,NaN

In [8]:
RentalList.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 9 columns):
LEASE NO.           174 non-null object
COUNTY              174 non-null object
STATE               174 non-null object
EXPIRATION          174 non-null datetime64[ns]
ACRES               174 non-null float64
RENTAL              174 non-null float64
COUNTY.1            18 non-null float64
Y/N                 0 non-null float64
Mishaun Comments    123 non-null object
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 12.3+ KB

In [9]:
#storing serial numbers found in RentalLis
SerialNumbers = RentalList.loc[:,"LEASE NO."]

SerialNumbers.dropna(inplace = True)

SerialNumbers

0       LAES57452
1       LAES57453
2       LAES57454
3       LAES57455
4       LAES57456
5       LAES57457
6       LAES57458
7       LAES57459
8       LAES57460
9       LAES57461
10      LAES57462
11      LAES57463
12      LAES57464
13      LAES57465
14      LAES57466
15      LAES57467
16      LAES57468
17      LAES57469
18      LAES57470
19      LAES57471
20     LAES056818
21     LAES056819
22     LAES056820
23     LAES056821
24     LAES056822
25     LAES056823
26     LAES056828
27     LAES056829
28     LAES056831
29     LAES056832
          ...
144     MSES57494
145     MSES57495
146     MSES57496
147     MSES57497
148     MSES57498
149    MSES056949
150    MSES056950
151    MSES056951
152    MSES056955
153    MSES056956
154    MSES056960
155    MSES056961
156    MSES056947
157    MSES056948
158    MSES056952
159    MSES056953
160    MSES056954
161    MSES056958
162    MSES056962
163    MSES056957
164    MSES056959
165     NDM101479
166      UTU92328
167      UTU92330
168      UTU92311
169      UTU92312
170      UTU92313
171      UTU92314
172      UTU92315
173      UTU92316
Name: LEASE NO., Length: 174, dtype: object

In [10]:
shapefile["LEASE_NO"]

0        NDM101156
1        NDM101159
2        NDM101160
3        NDM101164
4        NDM101166
5        NDM101169
6        NDM101172
7        NDM101173
8        NDM101180
9        MTM101455
10       MTM101456
11       MTM101458
12       MTM101464
13       MTM101465
14       MTM101475
15       MTM101477
16       NDM101479
17       NDM102132
18       NDM102136
19       NDM102130
20       SDM102222
21       SDM102219
22       SDM102226
23       SDM102664
24       SDM103746
25       SDM103748
26       SDM103750
27       SDM103751
28       SDM103758
29       SDM103761
           ...
1802     VAES55171
1803     VAES55161
1804     VAES55168
1805     VAES55163
1806     VAES55173
1807     VAES55158
1808     VAES55159
1809     VAES55176
1810     VAES55162
1811     VAES55169
1812    TXNM120401
1813     MIES55142
1814     MIES55146
1815     MIES55141
1816    TXNM119823
1817     MIES55147
1818     MIES55148
1819     VAES55172
1820     VAES55164
1821     VAES55174
1822     MIES55149
1823    TXNM119824
1824     MIES55145
1825    TXNM119822
1826     MIES55144
1827     MIES55151
1828     MIES55143
1829     MIES55152
1830     MIES55153
1831     MIES55154
Name: LEASE_NO, Length: 1832, dtype: object

In [11]:
#creating version of master shapefile with serial numbers found in the rental list
RentalShapeFile = shapefile.loc[shapefile["LEASE_NO"].isin(SerialNumbers)]

In [12]:
#checking lenghts of each variable to see if matches were found
RentalShapeFile["LEASE_NO"].count()
SerialNumbers.count()

164

174

# IF Mismatches - Section for Cleaning Lease Numbers Text

In [13]:
SerialNumbers[~SerialNumbers.isin(RentalShapeFile["LEASE_NO"])]

39    MSES056969*
41    MSES056971*
42    MSES056972*
43    MSES056973*
44    MSES056974*
45    MSES056976*
46    MSES056977*
47    MSES056980*
49    MSES057047*
75     MSES057011
Name: LEASE NO., dtype: object

In [14]:
testSerial = SerialNumbers.loc[39]

testSerial
re.findall('[\w]+', testSerial)[0]

'MSES056969*'

'MSES056969'

In [15]:
#creating function to run on a pandas series to clean up mistakenly placed special chars at end of serial number on rental spreadsheet
def replaceSpecialChars(serial):
    cleanedSerial = re.findall('[\w]+', serial)[0]
    return cleanedSerial

In [16]:
CleanedSerials = SerialNumbers.apply(lambda x: replaceSpecialChars(x))

In [17]:
RentalShapeFile = shapefile.loc[shapefile["LEASE_NO"].isin(CleanedSerials)]

In [18]:
RentalShapeFile["LEASE_NO"].count()
SerialNumbers.count()

173

174

In [19]:
CleanedSerials[~CleanedSerials.isin(RentalShapeFile["LEASE_NO"])]

75    MSES057011
Name: LEASE NO., dtype: object

# Writing RentalShapefile to File

In [20]:
RentalShapeFile.to_file(month + " 2020 - Rental Tracts.shp")

# Adding DI County Format for Filtering

In [21]:
states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}

In [22]:
#inversing dictionary
statetoInits = {v: k for k, v in states.items()}

In [23]:
#cleaning datatypes for State
RentalList.info()
RentalList["STATE"] = RentalList["STATE"].astype(str)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 9 columns):
LEASE NO.           174 non-null object
COUNTY              174 non-null object
STATE               174 non-null object
EXPIRATION          174 non-null datetime64[ns]
ACRES               174 non-null float64
RENTAL              174 non-null float64
COUNTY.1            18 non-null float64
Y/N                 0 non-null float64
Mishaun Comments    123 non-null object
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 12.3+ KB

In [24]:
#Adding Columnn with State abbreviations for each state by mapping state dictionary
RentalList["St. Initials"] = RentalList["STATE"].apply(lambda x: x.title()).map(statetoInits)

RentalList

,LEASE NO.,COUNTY,STATE,EXPIRATION,ACRES,RENTAL,COUNTY.1,Y/N,Mishaun Comments,St. Initials
0,LAES57452,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1998.57,3998.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
1,LAES57453,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,638.47,1278.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
2,LAES57454,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.63,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
3,LAES57455,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1154.67,2310.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
4,LAES57456,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.32,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
5,LAES57457,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.72,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
6,LAES57458,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.68,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
7,LAES57459,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2022.78,4046.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
8,LAES57460,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.68,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
9,LAES57461,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1273.80,2548.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
10,LAES57462,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,637.40,1276.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
11,LAES57463,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.52,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
12,LAES57464,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,591.10,1184.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
13,LAES57465,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,637.76,1276.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
14,LAES57466,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1274.00,2548.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
15,LAES57467,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2054.08,4110.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
16,LAES57468,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1911.48,3824.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
17,LAES57469,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1588.40,3178.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
18,LAES57470,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2498.37,4998.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA
19,LAES57471,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,89.10,180.0,44398.0,NaN,We renewed this blockcontiguous to this in ma...,LA
20,LAES056818,WINN PARISH,LOUISIANA,2021-08-01,39.55,80.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA
21,LAES056819,WINN PARISH,LOUISIANA,2021-08-01,377.03,756.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA
22,LAES056820,WINN PARISH,LOUISIANA,2021-08-01,757.41,1516.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA
23,LAES056821,WINN PARISH,LOUISIANA,2021-08-01,715.99,1432.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA
24,LAES056822,WINN PARISH,LOUISIANA,2021-08-01,1613.27,3228.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA
25,LAES056823,WINN PARISH,LOUISIANA,2021-08-01,242.37,486.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA
26,LAES056828,WINN PARISH,LOUISIANA,2021-08-01,79.64,160.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA
27,LAES056829,WINN PARISH,LOUISIANA,2021-08-01,79.66,160.0,NaN,NaN,JSB active operator to western part of this ac...,LA
28,LAES056831,WINN PARISH,LOUISIANA,2021-08-01,279.78,560.0,NaN,NaN,JSB active operator to western part of this ac...,LA
29,LAES056832,WINN PARISH,LOUISIANA,2021-08-01,79.69,160.0,NaN,NaN,JSB active operator to western part of this ac...,LA
...,...,...,...,...,...,...,...,...,...,...
144,MSES57494,FORREST,MISSISSIPPI,2022-08-01,2414.88,4830.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...,MS
145,MSES57495,FORREST,MISSISSIPPI,2022-08-01,1640.72,3282.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...,MS
146,MSES57496,FORREST,MISSISSIPPI,2022-08-01,80.00,160.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...,MS
147,MSES57497,FORREST,MISSISSIPPI,2022-08-01,200.00,400.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...,MS
148,MSES57498,FORREST,MISSISSIPPI,2022-08-01,40.00,80.0,8752.0,NaN,active shallow prod 1 -3 miles away from tract...,MS
149,MSES056949,HARRISON,MISSISSIPPI,2021-08-01,359.33,720.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
150,MSES056950,HARRISON,MISSISSIPPI,2021-08-01,399.53,800.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
151,MSES056951,HARRISON,MISSISSIPPI,2021-08-01,1236.33,2474.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
152,MSES056955,HARRISON,MISSISSIPPI,2021-08-01,1278.00,2556.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
153,MSES056956,HARRISON,MISSISSIPPI,2021-08-01,1277.40,2556.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
154,MSES056960,HARRISON,MISSISSIPPI,2021-08-01,1101.65,2204.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
155,MSES056961,HARRISON,MISSISSIPPI,2021-08-01,635.05,1272.0,12582.0,NaN,No active wells in the county - no permits - 1...,MS
156,MSES056947,JACKSON,MISSISSIPPI,2021-08-01,640.00,1280.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
157,MSES056948,JACKSON,MISSISSIPPI,2021-08-01,537.44,1076.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
158,MSES056952,JACKSON,MISSISSIPPI,2021-08-01,1154.53,2310.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
159,MSES056953,JACKSON,MISSISSIPPI,2021-08-01,804.76,1610.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
160,MSES056954,JACKSON,MISSISSIPPI,2021-08-01,957.28,1916.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
161,MSES056958,JACKSON,MISSISSIPPI,2021-08-01,1002.97,2006.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
162,MSES056962,JACKSON,MISSISSIPPI,2021-08-01,993.08,1988.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
163,MSES056957,JACKSON,MISSISSIPPI,2021-08-01,1324.52,2650.0,NaN,NaN,No active wells in the county - no permits - 1...,MS
164,MSES056959,JACKSON,MISSISSIPPI,2021-08-01,834.25,1670.0,16506.0,NaN,No active wells in the county - no permits - 1...,MS
165,NDM101479,MCKENZIE,NORTH DAKOTA,2021-08-01,120.69,242.0,242.0,NaN,NaN,ND
166,UTU92328,SANPETE,UTAH,2027-08-01,1239.20,1860.0,NaN,NaN,NaN,UT
167,UTU92330,SANPETE,UTAH,2027-08-01,1300.17,1951.5,3811.5,NaN,NaN,UT
168,UTU92311,SEVIER,UTAH,2027-08-01,200.00,300.0,NaN,NaN,NaN,UT
169,UTU92312,SEVIER,UTAH,2027-08-01,346.74,520.5,NaN,NaN,NaN,UT
170,UTU92313,SEVIER,UTAH,2027-08-01,200.00,300.0,NaN,NaN,NaN,UT
171,UTU92314,SEVIER,UTAH,2027-08-01,1482.76,2224.5,NaN,NaN,NaN,UT
172,UTU92315,SEVIER,UTAH,2027-08-01,2032.52,3049.5,NaN,NaN,NaN,UT
173,UTU92316,SEVIER,UTAH,2027-08-01,677.60,1017.0,7411.5,NaN,NaN,UT

In [25]:
#Creating Column with DI Counties Format Name
RentalList["DI Counties"] = RentalList["COUNTY"] + " (" + RentalList["St. Initials"] + ")"

In [26]:
RentalList

,LEASE NO.,COUNTY,STATE,EXPIRATION,ACRES,RENTAL,COUNTY.1,Y/N,Mishaun Comments,St. Initials,DI Counties
0,LAES57452,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1998.57,3998.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
1,LAES57453,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,638.47,1278.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
2,LAES57454,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.63,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
3,LAES57455,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1154.67,2310.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
4,LAES57456,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.32,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
5,LAES57457,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.72,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
6,LAES57458,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.68,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
7,LAES57459,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2022.78,4046.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
8,LAES57460,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.68,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
9,LAES57461,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1273.80,2548.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
10,LAES57462,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,637.40,1276.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
11,LAES57463,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,636.52,1274.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
12,LAES57464,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,591.10,1184.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
13,LAES57465,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,637.76,1276.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
14,LAES57466,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1274.00,2548.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
15,LAES57467,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2054.08,4110.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
16,LAES57468,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1911.48,3824.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
17,LAES57469,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,1588.40,3178.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
18,LAES57470,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,2498.37,4998.0,NaN,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
19,LAES57471,NATCHITOCHES PARISH,LOUISIANA,2022-08-01,89.10,180.0,44398.0,NaN,We renewed this blockcontiguous to this in ma...,LA,NATCHITOCHES PARISH (LA)
20,LAES056818,WINN PARISH,LOUISIANA,2021-08-01,39.55,80.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA,WINN PARISH (LA)
21,LAES056819,WINN PARISH,LOUISIANA,2021-08-01,377.03,756.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA,WINN PARISH (LA)
22,LAES056820,WINN PARISH,LOUISIANA,2021-08-01,757.41,1516.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA,WINN PARISH (LA)
23,LAES056821,WINN PARISH,LOUISIANA,2021-08-01,715.99,1432.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA,WINN PARISH (LA)
24,LAES056822,WINN PARISH,LOUISIANA,2021-08-01,1613.27,3228.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA,WINN PARISH (LA)
25,LAES056823,WINN PARISH,LOUISIANA,2021-08-01,242.37,486.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA,WINN PARISH (LA)
26,LAES056828,WINN PARISH,LOUISIANA,2021-08-01,79.64,160.0,NaN,NaN,active shallow production 3+ miles away in wil...,LA,WINN PARISH (LA)
27,LAES056829,WINN PARISH,LOUISIANA,2021-08-01,79.66,160.0,NaN,NaN,JSB active operator to western part of this ac...,LA,WINN PARISH (LA)
28,LAES056831,WINN PARISH,LOUISIANA,2021-08-01,279.78,560.0,NaN,NaN,JSB active operator to western part of this ac...,LA,WINN PARISH (LA)
29,LAES056832,WINN PARISH,LOUISIANA,2021-08-01,79.69,160.0,NaN,NaN,JSB active operator to western part of this ac...,LA,WINN PARISH (LA)
...,...,...,...,...,...,...,...,...,...,...,...
144,MSES57494,FORREST,MISSISSIPPI,2022-08-01,2414.88,4830.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...,MS,FORREST (MS)
145,MSES57495,FORREST,MISSISSIPPI,2022-08-01,1640.72,3282.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...,MS,FORREST (MS)
146,MSES57496,FORREST,MISSISSIPPI,2022-08-01,80.00,160.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...,MS,FORREST (MS)
147,MSES57497,FORREST,MISSISSIPPI,2022-08-01,200.00,400.0,NaN,NaN,active shallow prod 1 -3 miles away from tract...,MS,FORREST (MS)
148,MSES57498,FORREST,MISSISSIPPI,2022-08-01,40.00,80.0,8752.0,NaN,active shallow prod 1 -3 miles away from tract...,MS,FORREST (MS)
149,MSES056949,HARRISON,MISSISSIPPI,2021-08-01,359.33,720.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,HARRISON (MS)
150,MSES056950,HARRISON,MISSISSIPPI,2021-08-01,399.53,800.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,HARRISON (MS)
151,MSES056951,HARRISON,MISSISSIPPI,2021-08-01,1236.33,2474.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,HARRISON (MS)
152,MSES056955,HARRISON,MISSISSIPPI,2021-08-01,1278.00,2556.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,HARRISON (MS)
153,MSES056956,HARRISON,MISSISSIPPI,2021-08-01,1277.40,2556.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,HARRISON (MS)
154,MSES056960,HARRISON,MISSISSIPPI,2021-08-01,1101.65,2204.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,HARRISON (MS)
155,MSES056961,HARRISON,MISSISSIPPI,2021-08-01,635.05,1272.0,12582.0,NaN,No active wells in the county - no permits - 1...,MS,HARRISON (MS)
156,MSES056947,JACKSON,MISSISSIPPI,2021-08-01,640.00,1280.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,JACKSON (MS)
157,MSES056948,JACKSON,MISSISSIPPI,2021-08-01,537.44,1076.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,JACKSON (MS)
158,MSES056952,JACKSON,MISSISSIPPI,2021-08-01,1154.53,2310.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,JACKSON (MS)
159,MSES056953,JACKSON,MISSISSIPPI,2021-08-01,804.76,1610.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,JACKSON (MS)
160,MSES056954,JACKSON,MISSISSIPPI,2021-08-01,957.28,1916.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,JACKSON (MS)
161,MSES056958,JACKSON,MISSISSIPPI,2021-08-01,1002.97,2006.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,JACKSON (MS)
162,MSES056962,JACKSON,MISSISSIPPI,2021-08-01,993.08,1988.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,JACKSON (MS)
163,MSES056957,JACKSON,MISSISSIPPI,2021-08-01,1324.52,2650.0,NaN,NaN,No active wells in the county - no permits - 1...,MS,JACKSON (MS)
164,MSES056959,JACKSON,MISSISSIPPI,2021-08-01,834.25,1670.0,16506.0,NaN,No active wells in the county - no permits - 1...,MS,JACKSON (MS)
165,NDM101479,MCKENZIE,NORTH DAKOTA,2021-08-01,120.69,242.0,242.0,NaN,NaN,ND,MCKENZIE (ND)
166,UTU92328,SANPETE,UTAH,2027-08-01,1239.20,1860.0,NaN,NaN,NaN,UT,SANPETE (UT)
167,UTU92330,SANPETE,UTAH,2027-08-01,1300.17,1951.5,3811.5,NaN,NaN,UT,SANPETE (UT)
168,UTU92311,SEVIER,UTAH,2027-08-01,200.00,300.0,NaN,NaN,NaN,UT,SEVIER (UT)
169,UTU92312,SEVIER,UTAH,2027-08-01,346.74,520.5,NaN,NaN,NaN,UT,SEVIER (UT)
170,UTU92313,SEVIER,UTAH,2027-08-01,200.00,300.0,NaN,NaN,NaN,UT,SEVIER (UT)
171,UTU92314,SEVIER,UTAH,2027-08-01,1482.76,2224.5,NaN,NaN,NaN,UT,SEVIER (UT)
172,UTU92315,SEVIER,UTAH,2027-08-01,2032.52,3049.5,NaN,NaN,NaN,UT,SEVIER (UT)
173,UTU92316,SEVIER,UTAH,2027-08-01,677.60,1017.0,7411.5,NaN,NaN,UT,SEVIER (UT)

In [27]:
#output for DI counties - copy and paste into DI
for i in RentalList["DI Counties"].drop_duplicates():
    print(i)

NATCHITOCHES PARISH (LA)
WINN PARISH (LA)
ADAMS (MS)
AMITE (MS)
FRANKLIN (MS)
JASPER (MS)
SCOTT (MS)
WILKINSON (MS)
CLEBURNE (AR)
VAN BUREN (AR)
RIO BLANCO (CO)
RAPIDES PARISH (LA)
FORREST (MS)
HARRISON (MS)
JACKSON (MS)
JACKSON  (MS)
MCKENZIE (ND)
SANPETE (UT)
SEVIER (UT)

# Stat Summaries

In [28]:
RentalList.groupby(RentalList["EXPIRATION"].apply(lambda x: x.year)).sum()

               ACRES    RENTAL  COUNTY.1  Y/N
EXPIRATION
2021        50884.14  101846.0   87730.0  0.0
2022        37158.35   74350.0   88466.0  0.0
2023           22.16      46.0      46.0  0.0
2027        38195.91   57309.0   57309.0  0.0
2028         1604.68    2412.0    2412.0  0.0